### ISSUE TITLE
Implement/Document checkpointing

### ISSUE THREAD

**Issue by horenbergerb** [horenbergerb/FriendSimulator#4]
I think the current design does some kind of checkpointing or progress capture during training, but I'm not sure how it works. Adding this to the README would be very useful.

**Comment by debagos** [comment]
I am able now to load an trained model by checking if the output directory exists and then load from there:
```python
if os.path.isdir(output_dir):
	print("Loading existing model...")
	pt_model = GPT2LMHeadModel.from_pretrained("./"+output_dir)
	tokenizer = AutoTokenizer.from_pretrained("./"+output_dir, max_length=block_size, padding=True, truncate=True)
else:
	print("Creating new model...")
	pt_model = GPT2LMHeadModel.from_pretrained(model_name)
	tokenizer = AutoTokenizer.from_pretrained(model_name, max_length=block_size, padding=True, truncate=True)
```

**Comment by horenbergerb** [comment]
@debagos Thanks for working that out! Neat solution.
If you are interested in making a PR with the setting implemented, I would appreciate it! If you're unavailable, I'll try to take a look at this later in the week and update the repo.

**Comment by horenbergerb** [comment]
@debagos I implemented checkpointing according to your suggestion. Thanks for the help!
