### ISSUE TITLE
[Question] How to resume training?

### ISSUE THREAD

**Issue by debagos** [horenbergerb/FriendSimulator#6]
Hi :)

How do I resume training?
When I just call the training.py the training starts from the beginning again :disappointed:

**Comment by horenbergerb** [comment]
Hello,

Unfortunately I have not yet determined how to perform checkpointing. This is currently an open issue:
https://github.com/horenbergerb/FriendSimulator/issues/4

**Comment by debagos** [comment]
Ah I see, thank you for your reply :+1:
