### ISSUE TITLE
Errors on pip install -r requirements.txt

### ISSUE THREAD

**Issue by HalloweenMagic** [horenbergerb/FriendSimulator#7]
A lot of errors are generated when I try to use:

pip install -r requirements.txt

**Comment by horenbergerb** [comment]
I removed one line from the requirements that seemed to be incorrect, but otherwise it still works for me.

Are you using Python 3.x? Have you upgraded pip via `pip install --upgrade pip`?

**Comment by HalloweenMagic** [comment]
I'm using Python 3.10. pip upgraded to last version.
Windows 10 and also on Kali Linux.

```
ERROR: Could not find a version that satisfies the requirement torch==1.9.0 (from versions: 1.11.0, 1.12.0)
ERROR: No matching distribution found for torch==1.9.0
```

**Comment by TheFiZi** [comment]
Running into the same problem myself:

```bash
me@SAVORY:~/temp/FriendSimulator$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement torch==1.9.0 (from versions: 1.11.0, 1.12.0, 1.12.1)
ERROR: No matching distribution found for torch==1.9.0

me@SAVORY:~/temp/FriendSimulator$ python3 --version
Python 3.10.4

me@SAVORY:~/temp/FriendSimulator$ pip --version
pip 22.2.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
```

I edited `requirements.txt` and removed all of the explicit version number requirements and was able to get everything installed.

Will report back of your scripts work with the latest versions of these libraries.

**Comment by TheFiZi** [comment]
Yup. This `requirements.txt` worked fine for me

```
torch
dataclasses
PyYAML
transformers
```

**Comment by horenbergerb** [comment]
Updated the requirements.txt according to @TheFiZi. Thanks for the help!
